//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  skills: Skills;
  skillsConnection: SkillsConnection;
  education: Education;
  educationConnection: EducationConnection;
  experience: Experience;
  experienceConnection: ExperienceConnection;
  projects: Projects;
  projectsConnection: ProjectsConnection;
  certifications: Certifications;
  certificationsConnection: CertificationsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QuerySkillsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySkillsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
};


export type QueryEducationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEducationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EducationFilter>;
};


export type QueryExperienceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExperienceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
};


export type QueryProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
};


export type QueryCertificationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCertificationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CertificationsFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  skills?: InputMaybe<SkillsFilter>;
  education?: InputMaybe<EducationFilter>;
  experience?: InputMaybe<ExperienceFilter>;
  projects?: InputMaybe<ProjectsFilter>;
  certifications?: InputMaybe<CertificationsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Skills | Education | Experience | Projects | Certifications | Folder;

export type SiteHero = {
  __typename?: 'SiteHero';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  profileImage?: Maybe<Scalars['String']['output']>;
  resumeUrl?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  workstationImage?: Maybe<Scalars['String']['output']>;
  workstationImageAlt?: Maybe<Scalars['String']['output']>;
};

export type SiteStats = {
  __typename?: 'SiteStats';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['Float']['output']>;
  suffix?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type SiteAbout = {
  __typename?: 'SiteAbout';
  intro?: Maybe<Scalars['String']['output']>;
  objective?: Maybe<Scalars['String']['output']>;
  interests?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  strengths?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type SiteContact = {
  __typename?: 'SiteContact';
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  github?: Maybe<Scalars['String']['output']>;
  leetcode?: Maybe<Scalars['String']['output']>;
};

export type SiteSeo = {
  __typename?: 'SiteSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero?: Maybe<SiteHero>;
  stats?: Maybe<Array<Maybe<SiteStats>>>;
  about?: Maybe<SiteAbout>;
  contact?: Maybe<SiteContact>;
  seo?: Maybe<SiteSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteHeroFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  profileImage?: InputMaybe<ImageFilter>;
  resumeUrl?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  workstationImage?: InputMaybe<StringFilter>;
  workstationImageAlt?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SiteStatsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<NumberFilter>;
  suffix?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type SiteAboutFilter = {
  intro?: InputMaybe<StringFilter>;
  objective?: InputMaybe<StringFilter>;
  interests?: InputMaybe<StringFilter>;
  strengths?: InputMaybe<StringFilter>;
};

export type SiteContactFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
  leetcode?: InputMaybe<StringFilter>;
};

export type SiteSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  hero?: InputMaybe<SiteHeroFilter>;
  stats?: InputMaybe<SiteStatsFilter>;
  about?: InputMaybe<SiteAboutFilter>;
  contact?: InputMaybe<SiteContactFilter>;
  seo?: InputMaybe<SiteSeoFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type SkillsCategories = {
  __typename?: 'SkillsCategories';
  id?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  skills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Skills = Node & Document & {
  __typename?: 'Skills';
  categories?: Maybe<Array<Maybe<SkillsCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SkillsCategoriesFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  skills?: InputMaybe<StringFilter>;
};

export type SkillsFilter = {
  categories?: InputMaybe<SkillsCategoriesFilter>;
};

export type SkillsConnectionEdges = {
  __typename?: 'SkillsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Skills>;
};

export type SkillsConnection = Connection & {
  __typename?: 'SkillsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SkillsConnectionEdges>>>;
};

export type EducationEntries = {
  __typename?: 'EducationEntries';
  institution?: Maybe<Scalars['String']['output']>;
  degree?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  score?: Maybe<Scalars['String']['output']>;
  isCurrent?: Maybe<Scalars['Boolean']['output']>;
};

export type Education = Node & Document & {
  __typename?: 'Education';
  entries?: Maybe<Array<Maybe<EducationEntries>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EducationEntriesFilter = {
  institution?: InputMaybe<StringFilter>;
  degree?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  score?: InputMaybe<StringFilter>;
  isCurrent?: InputMaybe<BooleanFilter>;
};

export type EducationFilter = {
  entries?: InputMaybe<EducationEntriesFilter>;
};

export type EducationConnectionEdges = {
  __typename?: 'EducationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Education>;
};

export type EducationConnection = Connection & {
  __typename?: 'EducationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EducationConnectionEdges>>>;
};

export type ExperienceEntries = {
  __typename?: 'ExperienceEntries';
  role?: Maybe<Scalars['String']['output']>;
  organization?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  isCurrent?: Maybe<Scalars['Boolean']['output']>;
};

export type Experience = Node & Document & {
  __typename?: 'Experience';
  entries?: Maybe<Array<Maybe<ExperienceEntries>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ExperienceEntriesFilter = {
  role?: InputMaybe<StringFilter>;
  organization?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isCurrent?: InputMaybe<BooleanFilter>;
};

export type ExperienceFilter = {
  entries?: InputMaybe<ExperienceEntriesFilter>;
};

export type ExperienceConnectionEdges = {
  __typename?: 'ExperienceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Experience>;
};

export type ExperienceConnection = Connection & {
  __typename?: 'ExperienceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExperienceConnectionEdges>>>;
};

export type Projects = Node & Document & {
  __typename?: 'Projects';
  name?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  technologies?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  github?: Maybe<Scalars['String']['output']>;
  demo?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectsFilter = {
  name?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  technologies?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
  demo?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ProjectsConnectionEdges = {
  __typename?: 'ProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects>;
};

export type ProjectsConnection = Connection & {
  __typename?: 'ProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectsConnectionEdges>>>;
};

export type Certifications = Node & Document & {
  __typename?: 'Certifications';
  name?: Maybe<Scalars['String']['output']>;
  organization?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  issueDate?: Maybe<Scalars['String']['output']>;
  credentialUrl?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CertificationsFilter = {
  name?: InputMaybe<StringFilter>;
  organization?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  issueDate?: InputMaybe<StringFilter>;
  credentialUrl?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type CertificationsConnectionEdges = {
  __typename?: 'CertificationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Certifications>;
};

export type CertificationsConnection = Connection & {
  __typename?: 'CertificationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CertificationsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateSkills: Skills;
  createSkills: Skills;
  updateEducation: Education;
  createEducation: Education;
  updateExperience: Experience;
  createExperience: Experience;
  updateProjects: Projects;
  createProjects: Projects;
  updateCertifications: Certifications;
  createCertifications: Certifications;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationCreateSkillsArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillsMutation;
};


export type MutationUpdateEducationArgs = {
  relativePath: Scalars['String']['input'];
  params: EducationMutation;
};


export type MutationCreateEducationArgs = {
  relativePath: Scalars['String']['input'];
  params: EducationMutation;
};


export type MutationUpdateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationCreateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationUpdateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationCreateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationUpdateCertificationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CertificationsMutation;
};


export type MutationCreateCertificationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CertificationsMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  skills?: InputMaybe<SkillsMutation>;
  education?: InputMaybe<EducationMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  projects?: InputMaybe<ProjectsMutation>;
  certifications?: InputMaybe<CertificationsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  skills?: InputMaybe<SkillsMutation>;
  education?: InputMaybe<EducationMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  projects?: InputMaybe<ProjectsMutation>;
  certifications?: InputMaybe<CertificationsMutation>;
};

export type SiteHeroMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  profileImage?: InputMaybe<Scalars['String']['input']>;
  resumeUrl?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  workstationImage?: InputMaybe<Scalars['String']['input']>;
  workstationImageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type SiteStatsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['Float']['input']>;
  suffix?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type SiteAboutMutation = {
  intro?: InputMaybe<Scalars['String']['input']>;
  objective?: InputMaybe<Scalars['String']['input']>;
  interests?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  strengths?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteContactMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  github?: InputMaybe<Scalars['String']['input']>;
  leetcode?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero?: InputMaybe<SiteHeroMutation>;
  stats?: InputMaybe<Array<InputMaybe<SiteStatsMutation>>>;
  about?: InputMaybe<SiteAboutMutation>;
  contact?: InputMaybe<SiteContactMutation>;
  seo?: InputMaybe<SiteSeoMutation>;
};

export type SkillsCategoriesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  skills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SkillsMutation = {
  categories?: InputMaybe<Array<InputMaybe<SkillsCategoriesMutation>>>;
};

export type EducationEntriesMutation = {
  institution?: InputMaybe<Scalars['String']['input']>;
  degree?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  score?: InputMaybe<Scalars['String']['input']>;
  isCurrent?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EducationMutation = {
  entries?: InputMaybe<Array<InputMaybe<EducationEntriesMutation>>>;
};

export type ExperienceEntriesMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isCurrent?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ExperienceMutation = {
  entries?: InputMaybe<Array<InputMaybe<ExperienceEntriesMutation>>>;
};

export type ProjectsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  technologies?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  github?: InputMaybe<Scalars['String']['input']>;
  demo?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type CertificationsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  issueDate?: InputMaybe<Scalars['String']['input']>;
  credentialUrl?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SitePartsFragment = { __typename: 'Site', hero?: { __typename: 'SiteHero', name?: string | null, role?: string | null, tagline?: string | null, profileImage?: string | null, resumeUrl?: string | null, location?: string | null, workstationImage?: string | null, workstationImageAlt?: string | null } | null, stats?: Array<{ __typename: 'SiteStats', label?: string | null, value?: number | null, suffix?: string | null, icon?: string | null } | null> | null, about?: { __typename: 'SiteAbout', intro?: string | null, objective?: string | null, interests?: Array<string | null> | null, strengths?: Array<string | null> | null } | null, contact?: { __typename: 'SiteContact', email?: string | null, phone?: string | null, linkedin?: string | null, github?: string | null, leetcode?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null, keywords?: string | null } | null };

export type SkillsPartsFragment = { __typename: 'Skills', categories?: Array<{ __typename: 'SkillsCategories', id?: string | null, title?: string | null, icon?: string | null, skills?: Array<string | null> | null } | null> | null };

export type EducationPartsFragment = { __typename: 'Education', entries?: Array<{ __typename: 'EducationEntries', institution?: string | null, degree?: string | null, location?: string | null, period?: string | null, score?: string | null, isCurrent?: boolean | null } | null> | null };

export type ExperiencePartsFragment = { __typename: 'Experience', entries?: Array<{ __typename: 'ExperienceEntries', role?: string | null, organization?: string | null, period?: string | null, location?: string | null, description?: string | null, isCurrent?: boolean | null } | null> | null };

export type ProjectsPartsFragment = { __typename: 'Projects', name?: string | null, image?: string | null, description?: string | null, technologies?: Array<string | null> | null, github?: string | null, demo?: string | null, period?: string | null, featured?: boolean | null, order?: number | null };

export type CertificationsPartsFragment = { __typename: 'Certifications', name?: string | null, organization?: string | null, image?: string | null, issueDate?: string | null, credentialUrl?: string | null, order?: number | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', name?: string | null, role?: string | null, tagline?: string | null, profileImage?: string | null, resumeUrl?: string | null, location?: string | null, workstationImage?: string | null, workstationImageAlt?: string | null } | null, stats?: Array<{ __typename: 'SiteStats', label?: string | null, value?: number | null, suffix?: string | null, icon?: string | null } | null> | null, about?: { __typename: 'SiteAbout', intro?: string | null, objective?: string | null, interests?: Array<string | null> | null, strengths?: Array<string | null> | null } | null, contact?: { __typename: 'SiteContact', email?: string | null, phone?: string | null, linkedin?: string | null, github?: string | null, leetcode?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null, keywords?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', name?: string | null, role?: string | null, tagline?: string | null, profileImage?: string | null, resumeUrl?: string | null, location?: string | null, workstationImage?: string | null, workstationImageAlt?: string | null } | null, stats?: Array<{ __typename: 'SiteStats', label?: string | null, value?: number | null, suffix?: string | null, icon?: string | null } | null> | null, about?: { __typename: 'SiteAbout', intro?: string | null, objective?: string | null, interests?: Array<string | null> | null, strengths?: Array<string | null> | null } | null, contact?: { __typename: 'SiteContact', email?: string | null, phone?: string | null, linkedin?: string | null, github?: string | null, leetcode?: string | null } | null, seo?: { __typename: 'SiteSeo', title?: string | null, description?: string | null, keywords?: string | null } | null } | null } | null> | null } };

export type SkillsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SkillsQuery = { __typename?: 'Query', skills: { __typename: 'Skills', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'SkillsCategories', id?: string | null, title?: string | null, icon?: string | null, skills?: Array<string | null> | null } | null> | null } };

export type SkillsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillsFilter>;
}>;


export type SkillsConnectionQuery = { __typename?: 'Query', skillsConnection: { __typename?: 'SkillsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SkillsConnectionEdges', cursor: string, node?: { __typename: 'Skills', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'SkillsCategories', id?: string | null, title?: string | null, icon?: string | null, skills?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type EducationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EducationQuery = { __typename?: 'Query', education: { __typename: 'Education', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'EducationEntries', institution?: string | null, degree?: string | null, location?: string | null, period?: string | null, score?: string | null, isCurrent?: boolean | null } | null> | null } };

export type EducationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EducationFilter>;
}>;


export type EducationConnectionQuery = { __typename?: 'Query', educationConnection: { __typename?: 'EducationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EducationConnectionEdges', cursor: string, node?: { __typename: 'Education', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'EducationEntries', institution?: string | null, degree?: string | null, location?: string | null, period?: string | null, score?: string | null, isCurrent?: boolean | null } | null> | null } | null } | null> | null } };

export type ExperienceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExperienceQuery = { __typename?: 'Query', experience: { __typename: 'Experience', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'ExperienceEntries', role?: string | null, organization?: string | null, period?: string | null, location?: string | null, description?: string | null, isCurrent?: boolean | null } | null> | null } };

export type ExperienceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
}>;


export type ExperienceConnectionQuery = { __typename?: 'Query', experienceConnection: { __typename?: 'ExperienceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExperienceConnectionEdges', cursor: string, node?: { __typename: 'Experience', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'ExperienceEntries', role?: string | null, organization?: string | null, period?: string | null, location?: string | null, description?: string | null, isCurrent?: boolean | null } | null> | null } | null } | null> | null } };

export type ProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectsQuery = { __typename?: 'Query', projects: { __typename: 'Projects', id: string, name?: string | null, image?: string | null, description?: string | null, technologies?: Array<string | null> | null, github?: string | null, demo?: string | null, period?: string | null, featured?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
}>;


export type ProjectsConnectionQuery = { __typename?: 'Query', projectsConnection: { __typename?: 'ProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectsConnectionEdges', cursor: string, node?: { __typename: 'Projects', id: string, name?: string | null, image?: string | null, description?: string | null, technologies?: Array<string | null> | null, github?: string | null, demo?: string | null, period?: string | null, featured?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CertificationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CertificationsQuery = { __typename?: 'Query', certifications: { __typename: 'Certifications', id: string, name?: string | null, organization?: string | null, image?: string | null, issueDate?: string | null, credentialUrl?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CertificationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CertificationsFilter>;
}>;


export type CertificationsConnectionQuery = { __typename?: 'Query', certificationsConnection: { __typename?: 'CertificationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CertificationsConnectionEdges', cursor: string, node?: { __typename: 'Certifications', id: string, name?: string | null, organization?: string | null, image?: string | null, issueDate?: string | null, credentialUrl?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero {
    __typename
    name
    role
    tagline
    profileImage
    resumeUrl
    location
    workstationImage
    workstationImageAlt
  }
  stats {
    __typename
    label
    value
    suffix
    icon
  }
  about {
    __typename
    intro
    objective
    interests
    strengths
  }
  contact {
    __typename
    email
    phone
    linkedin
    github
    leetcode
  }
  seo {
    __typename
    title
    description
    keywords
  }
}
    `;
export const SkillsPartsFragmentDoc = gql`
    fragment SkillsParts on Skills {
  __typename
  categories {
    __typename
    id
    title
    icon
    skills
  }
}
    `;
export const EducationPartsFragmentDoc = gql`
    fragment EducationParts on Education {
  __typename
  entries {
    __typename
    institution
    degree
    location
    period
    score
    isCurrent
  }
}
    `;
export const ExperiencePartsFragmentDoc = gql`
    fragment ExperienceParts on Experience {
  __typename
  entries {
    __typename
    role
    organization
    period
    location
    description
    isCurrent
  }
}
    `;
export const ProjectsPartsFragmentDoc = gql`
    fragment ProjectsParts on Projects {
  __typename
  name
  image
  description
  technologies
  github
  demo
  period
  featured
  order
}
    `;
export const CertificationsPartsFragmentDoc = gql`
    fragment CertificationsParts on Certifications {
  __typename
  name
  organization
  image
  issueDate
  credentialUrl
  order
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const SkillsDocument = gql`
    query skills($relativePath: String!) {
  skills(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SkillsParts
  }
}
    ${SkillsPartsFragmentDoc}`;
export const SkillsConnectionDocument = gql`
    query skillsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SkillsFilter) {
  skillsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SkillsParts
      }
    }
  }
}
    ${SkillsPartsFragmentDoc}`;
export const EducationDocument = gql`
    query education($relativePath: String!) {
  education(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EducationParts
  }
}
    ${EducationPartsFragmentDoc}`;
export const EducationConnectionDocument = gql`
    query educationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EducationFilter) {
  educationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EducationParts
      }
    }
  }
}
    ${EducationPartsFragmentDoc}`;
export const ExperienceDocument = gql`
    query experience($relativePath: String!) {
  experience(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExperienceParts
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const ExperienceConnectionDocument = gql`
    query experienceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExperienceFilter) {
  experienceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExperienceParts
      }
    }
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const ProjectsDocument = gql`
    query projects($relativePath: String!) {
  projects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectsParts
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ProjectsConnectionDocument = gql`
    query projectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectsFilter) {
  projectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectsParts
      }
    }
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const CertificationsDocument = gql`
    query certifications($relativePath: String!) {
  certifications(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CertificationsParts
  }
}
    ${CertificationsPartsFragmentDoc}`;
export const CertificationsConnectionDocument = gql`
    query certificationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CertificationsFilter) {
  certificationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CertificationsParts
      }
    }
  }
}
    ${CertificationsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    skills(variables: SkillsQueryVariables, options?: C): Promise<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}> {
        return requester<{data: SkillsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsQueryVariables, query: string}, SkillsQueryVariables>(SkillsDocument, variables, options);
      },
    skillsConnection(variables?: SkillsConnectionQueryVariables, options?: C): Promise<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}> {
        return requester<{data: SkillsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillsConnectionQueryVariables, query: string}, SkillsConnectionQueryVariables>(SkillsConnectionDocument, variables, options);
      },
    education(variables: EducationQueryVariables, options?: C): Promise<{data: EducationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationQueryVariables, query: string}> {
        return requester<{data: EducationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationQueryVariables, query: string}, EducationQueryVariables>(EducationDocument, variables, options);
      },
    educationConnection(variables?: EducationConnectionQueryVariables, options?: C): Promise<{data: EducationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationConnectionQueryVariables, query: string}> {
        return requester<{data: EducationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationConnectionQueryVariables, query: string}, EducationConnectionQueryVariables>(EducationConnectionDocument, variables, options);
      },
    experience(variables: ExperienceQueryVariables, options?: C): Promise<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}> {
        return requester<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}, ExperienceQueryVariables>(ExperienceDocument, variables, options);
      },
    experienceConnection(variables?: ExperienceConnectionQueryVariables, options?: C): Promise<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}> {
        return requester<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}, ExperienceConnectionQueryVariables>(ExperienceConnectionDocument, variables, options);
      },
    projects(variables: ProjectsQueryVariables, options?: C): Promise<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}> {
        return requester<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}, ProjectsQueryVariables>(ProjectsDocument, variables, options);
      },
    projectsConnection(variables?: ProjectsConnectionQueryVariables, options?: C): Promise<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}, ProjectsConnectionQueryVariables>(ProjectsConnectionDocument, variables, options);
      },
    certifications(variables: CertificationsQueryVariables, options?: C): Promise<{data: CertificationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsQueryVariables, query: string}> {
        return requester<{data: CertificationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsQueryVariables, query: string}, CertificationsQueryVariables>(CertificationsDocument, variables, options);
      },
    certificationsConnection(variables?: CertificationsConnectionQueryVariables, options?: C): Promise<{data: CertificationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsConnectionQueryVariables, query: string}> {
        return requester<{data: CertificationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsConnectionQueryVariables, query: string}, CertificationsConnectionQueryVariables>(CertificationsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  